<a href="https://colab.research.google.com/github/Synthiya123/PYTHON/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Exercises

In [1]:
import numpy as np

Exercise 1



*   Create an 1d array
*   Create a the given matrix.



In [7]:
# 1d Array

l=[7, 9, 65, 33, 85, 99]
od = np.array(l)
print(od)

[ 7  9 65 33 85 99]


In [27]:
# Matrix

A = [[1,2,4],[2,3,0],[0,5,1]] 
td= np.array(A)
print('A=\n', td)

A=
 [[1 2 4]
 [2 3 0]
 [0 5 1]]


In [28]:
# changing the order of matrix.

orma= np.array(A).reshape(9,1)
print(orma)


[[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]


In [29]:
ord_mat= np.array(A).reshape(3,3)
print(ord_mat)


[[1 2 4]
 [2 3 0]
 [0 5 1]]


# Array Generation

*   .arange
*   .linspace


*   .repeat

*    .eye





In [31]:
# .arange()

sd= np.arange(20,50)
sd

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [39]:
sd1= np.arange(20,50,5)
sd1

array([20, 25, 30, 35, 40, 45])

In [33]:
sd1= np.arange(20,50).reshape(5,6)
sd1


array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [36]:
# .linspace - Generates the decimals values of evenly spaced.
sid= np.linspace(10,20)
sid

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [37]:
sid= np.linspace(10,20,10)
sid

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [44]:
# repeat

re_sd1= np.repeat(5,8)
re_sd1



array([5, 5, 5, 5, 5, 5, 5, 5])

In [47]:
re_sd1= np.repeat((15,25),(8,5))
re_sd1


array([15, 15, 15, 15, 15, 15, 15, 15, 25, 25, 25, 25, 25])

In [49]:
#.eye - Indentity Matrix

E= np.eye(5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#Operations

In [50]:
sd1

array([20, 25, 30, 35, 40, 45])

In [52]:
print('Product:', 3 * sd1)
print("Add:", 15 + sd1)
print("Sub:", sd1 - 5)
print("Divi:", sd1/5)
print("Expo:", sd1 **3)
print("Boole:", sd1 < 30)

Product: [ 60  75  90 105 120 135]
Add: [35 40 45 50 55 60]
Sub: [15 20 25 30 35 40]
Divi: [4. 5. 6. 7. 8. 9.]
Expo: [ 8000 15625 27000 42875 64000 91125]
Boole: [ True  True False False False False]


#Speed Test

In [54]:
# Two data types  

tdt= list(range(250,350,5))
tdt


[250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345]

In [56]:
%timeit sd1*4

904 ns ± 14.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [58]:
%timeit [i+ 10 for i in sd1]

2.58 µs ± 57.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


STRINGS





In [63]:
data_types= np.array(["list","array","strings","Tuples","Dictionary"])
print(np.isin(data_types, "i"))
print("i" in data_types)
["i" in data_types for data_types in data_types]




[False False False False False]
False


[True, False, True, False, True]

#Transpose

In [72]:
sd
sd.shape=(3,2)
print(sd,"\n")
print(sd.T)


[[20 25]
 [30 35]
 [40 45]] 

[[20 30 40]
 [25 35 45]]


#Exercise 2

In [88]:
W.dtype

dtype('<U21')

In [85]:

W = np.array([33,'25','65','78','67','98','54'])
W

array(['33', '25', '65', '78', '67', '98', '54'], dtype='<U21')

In [158]:
# Convert the string number to float.

W = np.array(['25','65','78','67','98','54'],dtype='float32')
W

array([25., 65., 78., 67., 98., 54.], dtype=float32)

In [95]:
# Transpose the matrix - new size snd shape

T= np.arange (10,20)
T


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [96]:
T.size



10

In [97]:
T.shape

(10,)

In [98]:
#convert array to boolean
 
A1.astype('int32')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int32)

In [100]:
T.astype('bool')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [105]:
I=np.eye(3)
I.astype('bool')

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

#Exercise 3

In [106]:
# 50 zeros

np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
#Repeat 2 twenty times

np.repeat(2,20)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [120]:
pi=3.14*2
pi

6.28

In [123]:
# Array through function Range

Ar= np.arange(0,pi,0.1)
print(Ar)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2]


In [126]:
# first 5 elements

Ar[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [129]:
# Last 3 elements

Ar.size
Ar[60:]

array([6. , 6.1, 6.2])

In [131]:
# Elements between 4th to 8th

Ar[4:8]

array([0.4, 0.5, 0.6, 0.7])

#Exercise 4

In [150]:
#Reverse an array

rev_Ar=np.flip(Ar)
rev_Ar

array([6.2, 6.1, 6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5. ,
       4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9, 3.8, 3.7,
       3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4,
       2.3, 2.2, 2.1, 2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1,
       1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [152]:
# Get 4th elements

rev_Ar[0::4]

array([6.2, 5.8, 5.4, 5. , 4.6, 4.2, 3.8, 3.4, 3. , 2.6, 2.2, 1.8, 1.4,
       1. , 0.6, 0.2])

In [156]:
#Get every 2nd element, starting from the last and moving backwards.

rev_Ar[::-2]


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2])

In [154]:
Ar.size

63

#Exercise 5   

In [133]:
# Descrptive stats

nums = np.arange(0, 4, 0.2555)


In [134]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


#Exercise 6


In [142]:
#Generate a list of values from 10 throws of a six sided dice.

dice_roll = np.random.choice(list(range(0,7)), 10)
dice_roll

array([5, 1, 3, 1, 6, 2, 6, 1, 1, 1])

In [148]:
# coin is tossed twice as likely to have head than tails.
ran_flip = np.random.choice([1,1,0], 10)
ran_flip

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1])